### ISSUE TITLE
Not syncing

### ISSUE THREAD

**Issue by prabu96** [remnoteio/twtterbotplugin#3]
I am not able to sync my email and twitter to my remnote. But I used it before... after I linked it. Now, it is not working. I send lot of mail and shared so many tweets. but still it is not working.

**Comment by Hcg-dev** [comment]
Hi, saving something on twitter to my Remnote knowledge base is a crucial part of my research flow. I have the same syncing problem. I was using RemnoteTwitterBot which was quiet beneficial. And I was checking a replacement plugin since the major Remnote update. But still waiting for a working plugin solution from Remnote community. Thank you in advance for any effort.

**Comment by bjsi** [comment]
Thanks for the reports everyone, I just uploaded the fixed version of the plugin. Let me know if there are any more issues!
